/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'chemadvisor.chemApi.model/ApiResponseMessage', 'chemadvisor.chemApi.model/RelatedSubstances', 'chemadvisor.chemApi.model/Substance', 'chemadvisor.chemApi.model/Identifiers', 'chemadvisor.chemApi.model/Inventories', 'chemadvisor.chemApi.model/RegulatoryLists', 'chemadvisor.chemApi.model/SubstanceNames', 'chemadvisor.chemApi.model/Substances'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../chemadvisor.chemApi.model/ApiResponseMessage'), require('../chemadvisor.chemApi.model/RelatedSubstances'), require('../chemadvisor.chemApi.model/Substance'), require('../chemadvisor.chemApi.model/Identifiers'), require('../chemadvisor.chemApi.model/Inventories'), require('../chemadvisor.chemApi.model/RegulatoryLists'), require('../chemadvisor.chemApi.model/SubstanceNames'), require('../chemadvisor.chemApi.model/Substances'));
  } else {
    // Browser globals (root is window)
    if (!root.ChemadvisorChemApi) {
      root.ChemadvisorChemApi = {};
    }
    root.ChemadvisorChemApi.SubstancesApi = factory(root.ChemadvisorChemApi.ApiClient, root.ChemadvisorChemApi.ApiResponseMessage, root.ChemadvisorChemApi.RelatedSubstances, root.ChemadvisorChemApi.Substance, root.ChemadvisorChemApi.Identifiers, root.ChemadvisorChemApi.Inventories, root.ChemadvisorChemApi.RegulatoryLists, root.ChemadvisorChemApi.SubstanceNames, root.ChemadvisorChemApi.Substances);
  }
}(this, function(ApiClient, ApiResponseMessage, RelatedSubstances, Substance, Identifiers, Inventories, RegulatoryLists, SubstanceNames, Substances) {
  'use strict';

  /**
   * Substances service.
   * @module chemadvisor.chemApi.client/SubstancesApi
   * @version 0.9.6 beta
   */

  /**
   * Constructs a new SubstancesApi. 
   * @alias module:chemadvisor.chemApi.client/SubstancesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getRelatedSubstances operation.
     * @callback module:chemadvisor.chemApi.client/SubstancesApi~getRelatedSubstancesCallback
     * @param {String} error Error message, if any.
     * @param {module:chemadvisor.chemApi.model/RelatedSubstances} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Links to related substances
     * Returns a collection of links to related substances
     * @param {String} substanceId Substance id
     * @param {Object} opts Optional parameters
     * @param {String} opts.appKey 
     * @param {String} opts.appId 
     * @param {module:chemadvisor.chemApi.client/SubstancesApi~getRelatedSubstancesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:chemadvisor.chemApi.model/RelatedSubstances}
     */
    this.getRelatedSubstances = function(substanceId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'substanceId' is set
      if (substanceId == undefined || substanceId == null) {
        throw "Missing the required parameter 'substanceId' when calling getRelatedSubstances";
      }


      var pathParams = {
        'substance_id': substanceId
      };
      var queryParams = {
      };
      var headerParams = {
        'app_key': opts['appKey'],
        'app_id': opts['appId']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = RelatedSubstances;

      return this.apiClient.callApi(
        '/substances/{substance_id}/related_substances', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubstance operation.
     * @callback module:chemadvisor.chemApi.client/SubstancesApi~getSubstanceCallback
     * @param {String} error Error message, if any.
     * @param {module:chemadvisor.chemApi.model/Substance} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find substance by ID
     * Returns a single substance
     * @param {String} substanceId Substance id
     * @param {Object} opts Optional parameters
     * @param {String} opts.appKey 
     * @param {String} opts.appId 
     * @param {module:chemadvisor.chemApi.client/SubstancesApi~getSubstanceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:chemadvisor.chemApi.model/Substance}
     */
    this.getSubstance = function(substanceId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'substanceId' is set
      if (substanceId == undefined || substanceId == null) {
        throw "Missing the required parameter 'substanceId' when calling getSubstance";
      }


      var pathParams = {
        'substance_id': substanceId
      };
      var queryParams = {
      };
      var headerParams = {
        'app_key': opts['appKey'],
        'app_id': opts['appId']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = Substance;

      return this.apiClient.callApi(
        '/substances/{substance_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubstanceIdentifiers operation.
     * @callback module:chemadvisor.chemApi.client/SubstancesApi~getSubstanceIdentifiersCallback
     * @param {String} error Error message, if any.
     * @param {module:chemadvisor.chemApi.model/Identifiers} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * A substance&#39;s public identifiers
     * Returns a collection of public identifiers for a substance.
     * @param {String} substanceId Substance id
     * @param {Object} opts Optional parameters
     * @param {String} opts.appKey 
     * @param {String} opts.appId 
     * @param {module:chemadvisor.chemApi.client/SubstancesApi~getSubstanceIdentifiersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:chemadvisor.chemApi.model/Identifiers}
     */
    this.getSubstanceIdentifiers = function(substanceId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'substanceId' is set
      if (substanceId == undefined || substanceId == null) {
        throw "Missing the required parameter 'substanceId' when calling getSubstanceIdentifiers";
      }


      var pathParams = {
        'substance_id': substanceId
      };
      var queryParams = {
      };
      var headerParams = {
        'app_key': opts['appKey'],
        'app_id': opts['appId']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = Identifiers;

      return this.apiClient.callApi(
        '/substances/{substance_id}/identifiers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubstanceInventoryHits operation.
     * @callback module:chemadvisor.chemApi.client/SubstancesApi~getSubstanceInventoryHitsCallback
     * @param {String} error Error message, if any.
     * @param {module:chemadvisor.chemApi.model/Inventories} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * A substance&#39;s inventory status
     * Returns a collection of inventory objects for a substance
     * @param {String} substanceId Substance id
     * @param {Object} opts Optional parameters
     * @param {String} opts.appKey 
     * @param {String} opts.appId 
     * @param {module:chemadvisor.chemApi.client/SubstancesApi~getSubstanceInventoryHitsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:chemadvisor.chemApi.model/Inventories}
     */
    this.getSubstanceInventoryHits = function(substanceId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'substanceId' is set
      if (substanceId == undefined || substanceId == null) {
        throw "Missing the required parameter 'substanceId' when calling getSubstanceInventoryHits";
      }


      var pathParams = {
        'substance_id': substanceId
      };
      var queryParams = {
      };
      var headerParams = {
        'app_key': opts['appKey'],
        'app_id': opts['appId']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = Inventories;

      return this.apiClient.callApi(
        '/substances/{substance_id}/inventories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubstanceListHits operation.
     * @callback module:chemadvisor.chemApi.client/SubstancesApi~getSubstanceListHitsCallback
     * @param {String} error Error message, if any.
     * @param {module:chemadvisor.chemApi.model/RegulatoryLists} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * LOLI lists containing this substance
     * Returns a paginated collection of list objects for lists contain this substance
     * @param {String} substanceId Substance ID
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.limit Number of items to retrieve (default to 10)
     * @param {Integer} opts.offset Offset of the first item returned (default to 0)
     * @param {String} opts.q Search filter is based on the syntax used for find in mongoDB.  For more information, visit &lt;a href&#x3D;\&quot;https://developer.chemadvisor.io/docs/integrate/codeExamplesQ\&quot; target&#x3D;\&quot;blank\&quot;&gt;https://developer.chemadvisor.io/docs/integrate/codeExamplesQ&lt;/a&gt;.
     * @param {String} opts.appKey 
     * @param {String} opts.appId 
     * @param {module:chemadvisor.chemApi.client/SubstancesApi~getSubstanceListHitsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:chemadvisor.chemApi.model/RegulatoryLists}
     */
    this.getSubstanceListHits = function(substanceId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'substanceId' is set
      if (substanceId == undefined || substanceId == null) {
        throw "Missing the required parameter 'substanceId' when calling getSubstanceListHits";
      }


      var pathParams = {
        'substance_id': substanceId
      };
      var queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'q': opts['q']
      };
      var headerParams = {
        'app_key': opts['appKey'],
        'app_id': opts['appId']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = RegulatoryLists;

      return this.apiClient.callApi(
        '/substances/{substance_id}/regulatory_lists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubstanceNames operation.
     * @callback module:chemadvisor.chemApi.client/SubstancesApi~getSubstanceNamesCallback
     * @param {String} error Error message, if any.
     * @param {module:chemadvisor.chemApi.model/SubstanceNames} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a Specific Substance&#39;s names
     * Gets a collection of **name** objects Required path param of &#39;substance_id&#39; 
     * @param {String} substanceId Identifier for the substance
     * @param {Object} opts Optional parameters
     * @param {String} opts.appKey 
     * @param {String} opts.appId 
     * @param {module:chemadvisor.chemApi.client/SubstancesApi~getSubstanceNamesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:chemadvisor.chemApi.model/SubstanceNames}
     */
    this.getSubstanceNames = function(substanceId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'substanceId' is set
      if (substanceId == undefined || substanceId == null) {
        throw "Missing the required parameter 'substanceId' when calling getSubstanceNames";
      }


      var pathParams = {
        'substance_id': substanceId
      };
      var queryParams = {
      };
      var headerParams = {
        'app_key': opts['appKey'],
        'app_id': opts['appId']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = SubstanceNames;

      return this.apiClient.callApi(
        '/substances/{substance_id}/names', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubstances operation.
     * @callback module:chemadvisor.chemApi.client/SubstancesApi~getSubstancesCallback
     * @param {String} error Error message, if any.
     * @param {module:chemadvisor.chemApi.model/Substances} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * All Substances
     * A paginated collection of substances
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.limit Number of items to retrieve (default to 10)
     * @param {Integer} opts.offset Offset of the first item returned (default to 0)
     * @param {String} opts.q Search filter is based on the syntax used for find in mongoDB.  For more information, visit &lt;a href&#x3D;\&quot;https://developer.chemadvisor.io/docs/integrate/codeExamplesQ\&quot; target&#x3D;\&quot;blank\&quot;&gt;https://developer.chemadvisor.io/docs/integrate/codeExamplesQ&lt;/a&gt;.
     * @param {String} opts.appKey 
     * @param {String} opts.appId 
     * @param {module:chemadvisor.chemApi.client/SubstancesApi~getSubstancesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:chemadvisor.chemApi.model/Substances}
     */
    this.getSubstances = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'q': opts['q']
      };
      var headerParams = {
        'app_key': opts['appKey'],
        'app_id': opts['appId']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = Substances;

      return this.apiClient.callApi(
        '/substances', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
