/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'chemadvisor.chemApi.model/ApiResponseMessage', 'chemadvisor.chemApi.model/EntryChanges', 'chemadvisor.chemApi.model/RegulatoryListChanges'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../chemadvisor.chemApi.model/ApiResponseMessage'), require('../chemadvisor.chemApi.model/EntryChanges'), require('../chemadvisor.chemApi.model/RegulatoryListChanges'));
  } else {
    // Browser globals (root is window)
    if (!root.ChemadvisorChemApi) {
      root.ChemadvisorChemApi = {};
    }
    root.ChemadvisorChemApi.UpdatesApi = factory(root.ChemadvisorChemApi.ApiClient, root.ChemadvisorChemApi.ApiResponseMessage, root.ChemadvisorChemApi.EntryChanges, root.ChemadvisorChemApi.RegulatoryListChanges);
  }
}(this, function(ApiClient, ApiResponseMessage, EntryChanges, RegulatoryListChanges) {
  'use strict';

  /**
   * Updates service.
   * @module chemadvisor.chemApi.client/UpdatesApi
   * @version 0.9.6 beta
   */

  /**
   * Constructs a new UpdatesApi. 
   * @alias module:chemadvisor.chemApi.client/UpdatesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getEntryUpdate operation.
     * @callback module:chemadvisor.chemApi.client/UpdatesApi~getEntryUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:chemadvisor.chemApi.model/EntryChanges} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Specific Regulatory Data Updates that were released after release_id
     * Returns an **EntryChanges** collection. 
     * @param {String} releaseId Release ID
     * @param {String} substanceId Substance ID
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.limit Number of items to retrieve (default to 10)
     * @param {Integer} opts.offset Offset of the first item returned (default to 0)
     * @param {String} opts.appKey 
     * @param {String} opts.appId 
     * @param {module:chemadvisor.chemApi.client/UpdatesApi~getEntryUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:chemadvisor.chemApi.model/EntryChanges}
     */
    this.getEntryUpdate = function(releaseId, substanceId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'releaseId' is set
      if (releaseId == undefined || releaseId == null) {
        throw "Missing the required parameter 'releaseId' when calling getEntryUpdate";
      }

      // verify the required parameter 'substanceId' is set
      if (substanceId == undefined || substanceId == null) {
        throw "Missing the required parameter 'substanceId' when calling getEntryUpdate";
      }


      var pathParams = {
        'release_id': releaseId,
        'substance_id': substanceId
      };
      var queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      var headerParams = {
        'app_key': opts['appKey'],
        'app_id': opts['appId']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json', 'application/xml'];
      var returnType = EntryChanges;

      return this.apiClient.callApi(
        '/updates_since/{release_id}/entry_changes/{substance_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getListUpdates operation.
     * @callback module:chemadvisor.chemApi.client/UpdatesApi~getListUpdatesCallback
     * @param {String} error Error message, if any.
     * @param {module:chemadvisor.chemApi.model/RegulatoryListChanges} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All List additions and removals released after release_id
     * Returns a **RegulatoryListChanges** object. 
     * @param {String} releaseId Release ID
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.limit Number of items to retrieve (default to 10)
     * @param {Integer} opts.offset Offset of the first item returned (default to 0)
     * @param {String} opts.appKey 
     * @param {String} opts.appId 
     * @param {module:chemadvisor.chemApi.client/UpdatesApi~getListUpdatesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:chemadvisor.chemApi.model/RegulatoryListChanges}
     */
    this.getListUpdates = function(releaseId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'releaseId' is set
      if (releaseId == undefined || releaseId == null) {
        throw "Missing the required parameter 'releaseId' when calling getListUpdates";
      }


      var pathParams = {
        'release_id': releaseId
      };
      var queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      var headerParams = {
        'app_key': opts['appKey'],
        'app_id': opts['appId']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/xml', 'application/json'];
      var returnType = RegulatoryListChanges;

      return this.apiClient.callApi(
        '/updates_since/{release_id}/regulatory_list_changes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
