/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ChemadvisorChemApi) {
      root.ChemadvisorChemApi = {};
    }
    root.ChemadvisorChemApi.BaseDataType = factory(root.ChemadvisorChemApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BaseDataType model module.
   * @module chemadvisor.chemApi.model/BaseDataType
   * @version 0.9.6 beta
   */

  /**
   * Constructs a new <code>BaseDataType</code>.
   * Basic class for data types
   * @alias module:chemadvisor.chemApi.model/BaseDataType
   * @class
   * @param dataType {String} 
   * @param name {String} 
   * @param prompt {String} 
   * @param value {String} 
   */
  var exports = function(dataType, name, prompt, value) {
    var _this = this;

    _this['data_type'] = dataType;
    _this['name'] = name;
    _this['prompt'] = prompt;
    _this['value'] = value;
  };

  /**
   * Constructs a <code>BaseDataType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:chemadvisor.chemApi.model/BaseDataType} obj Optional instance to populate.
   * @return {module:chemadvisor.chemApi.model/BaseDataType} The populated <code>BaseDataType</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data_type')) {
        obj['data_type'] = ApiClient.convertToType(data['data_type'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('prompt')) {
        obj['prompt'] = ApiClient.convertToType(data['prompt'], 'String');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} data_type
   */
  exports.prototype['data_type'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} prompt
   */
  exports.prototype['prompt'] = undefined;
  /**
   * @member {String} value
   */
  exports.prototype['value'] = undefined;



  return exports;
}));


