/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'chemadvisor.chemApi.model/Links'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Links'));
  } else {
    // Browser globals (root is window)
    if (!root.ChemadvisorChemApi) {
      root.ChemadvisorChemApi = {};
    }
    root.ChemadvisorChemApi.EntryChange = factory(root.ChemadvisorChemApi.ApiClient, root.ChemadvisorChemApi.Links);
  }
}(this, function(ApiClient, Links) {
  'use strict';




  /**
   * The EntryChange model module.
   * @module chemadvisor.chemApi.model/EntryChange
   * @version 0.9.6 beta
   */

  /**
   * Constructs a new <code>EntryChange</code>.
   * @alias module:chemadvisor.chemApi.model/EntryChange
   * @class
   * @param id {String} 
   * @param changeType {String} 
   * @param regulatoryListId {Integer} 
   * @param substanceId {Integer} 
   * @param releaseId {Integer} 
   */
  var exports = function(id, changeType, regulatoryListId, substanceId, releaseId) {
    var _this = this;

    _this['_id'] = id;
    _this['change_type'] = changeType;
    _this['regulatory_list_id'] = regulatoryListId;
    _this['substance_id'] = substanceId;
    _this['release_id'] = releaseId;

  };

  /**
   * Constructs a <code>EntryChange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:chemadvisor.chemApi.model/EntryChange} obj Optional instance to populate.
   * @return {module:chemadvisor.chemApi.model/EntryChange} The populated <code>EntryChange</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('change_type')) {
        obj['change_type'] = ApiClient.convertToType(data['change_type'], 'String');
      }
      if (data.hasOwnProperty('regulatory_list_id')) {
        obj['regulatory_list_id'] = ApiClient.convertToType(data['regulatory_list_id'], 'Integer');
      }
      if (data.hasOwnProperty('substance_id')) {
        obj['substance_id'] = ApiClient.convertToType(data['substance_id'], 'Integer');
      }
      if (data.hasOwnProperty('release_id')) {
        obj['release_id'] = ApiClient.convertToType(data['release_id'], 'Integer');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = Links.constructFromObject(data['links']);
      }
    }
    return obj;
  }

  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {String} change_type
   */
  exports.prototype['change_type'] = undefined;
  /**
   * @member {Integer} regulatory_list_id
   */
  exports.prototype['regulatory_list_id'] = undefined;
  /**
   * @member {Integer} substance_id
   */
  exports.prototype['substance_id'] = undefined;
  /**
   * @member {Integer} release_id
   */
  exports.prototype['release_id'] = undefined;
  /**
   * @member {module:chemadvisor.chemApi.model/Links} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


