/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'chemadvisor.chemApi.model/BaseDataType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BaseDataType'));
  } else {
    // Browser globals (root is window)
    if (!root.ChemadvisorChemApi) {
      root.ChemadvisorChemApi = {};
    }
    root.ChemadvisorChemApi.Fields = factory(root.ChemadvisorChemApi.ApiClient, root.ChemadvisorChemApi.BaseDataType);
  }
}(this, function(ApiClient, BaseDataType) {
  'use strict';




  /**
   * The Fields model module.
   * @module chemadvisor.chemApi.model/Fields
   * @version 0.9.6 beta
   */

  /**
   * Constructs a new <code>Fields</code>.
   * @alias module:chemadvisor.chemApi.model/Fields
   * @class
   * @param field {Array.<module:chemadvisor.chemApi.model/BaseDataType>} A collection of data_type objects
   */
  var exports = function(field) {
    var _this = this;

    _this['field'] = field;
  };

  /**
   * Constructs a <code>Fields</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:chemadvisor.chemApi.model/Fields} obj Optional instance to populate.
   * @return {module:chemadvisor.chemApi.model/Fields} The populated <code>Fields</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('field')) {
        obj['field'] = ApiClient.convertToType(data['field'], [BaseDataType]);
      }
    }
    return obj;
  }

  /**
   * A collection of data_type objects
   * @member {Array.<module:chemadvisor.chemApi.model/BaseDataType>} field
   */
  exports.prototype['field'] = undefined;



  return exports;
}));


