/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'chemadvisor.chemApi.model/Language'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Language'));
  } else {
    // Browser globals (root is window)
    if (!root.ChemadvisorChemApi) {
      root.ChemadvisorChemApi = {};
    }
    root.ChemadvisorChemApi.Languages = factory(root.ChemadvisorChemApi.ApiClient, root.ChemadvisorChemApi.Language);
  }
}(this, function(ApiClient, Language) {
  'use strict';




  /**
   * The Languages model module.
   * @module chemadvisor.chemApi.model/Languages
   * @version 0.9.6 beta
   */

  /**
   * Constructs a new <code>Languages</code>.
   * @alias module:chemadvisor.chemApi.model/Languages
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>Languages</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:chemadvisor.chemApi.model/Languages} obj Optional instance to populate.
   * @return {module:chemadvisor.chemApi.model/Languages} The populated <code>Languages</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('language')) {
        obj['language'] = ApiClient.convertToType(data['language'], [Language]);
      }
    }
    return obj;
  }

  /**
   * A collection of language objects
   * @member {Array.<module:chemadvisor.chemApi.model/Language>} language
   */
  exports.prototype['language'] = undefined;



  return exports;
}));


