/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ChemadvisorChemApi) {
      root.ChemadvisorChemApi = {};
    }
    root.ChemadvisorChemApi.Language = factory(root.ChemadvisorChemApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Language model module.
   * @module chemadvisor.chemApi.model/Language
   * @version 0.9.6 beta
   */

  /**
   * Constructs a new <code>Language</code>.
   * @alias module:chemadvisor.chemApi.model/Language
   * @class
   * @param iso6391Language {String} 
   * @param iso6391Code {String} 
   */
  var exports = function(iso6391Language, iso6391Code) {
    var _this = this;

    _this['iso_639_1_language'] = iso6391Language;
    _this['iso_639_1_code'] = iso6391Code;
  };

  /**
   * Constructs a <code>Language</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:chemadvisor.chemApi.model/Language} obj Optional instance to populate.
   * @return {module:chemadvisor.chemApi.model/Language} The populated <code>Language</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('iso_639_1_language')) {
        obj['iso_639_1_language'] = ApiClient.convertToType(data['iso_639_1_language'], 'String');
      }
      if (data.hasOwnProperty('iso_639_1_code')) {
        obj['iso_639_1_code'] = ApiClient.convertToType(data['iso_639_1_code'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} iso_639_1_language
   */
  exports.prototype['iso_639_1_language'] = undefined;
  /**
   * @member {String} iso_639_1_code
   */
  exports.prototype['iso_639_1_code'] = undefined;



  return exports;
}));


