/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'chemadvisor.chemApi.model/Entries', 'chemadvisor.chemApi.model/Languages', 'chemadvisor.chemApi.model/Links', 'chemadvisor.chemApi.model/Tags'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Entries'), require('./Languages'), require('./Links'), require('./Tags'));
  } else {
    // Browser globals (root is window)
    if (!root.ChemadvisorChemApi) {
      root.ChemadvisorChemApi = {};
    }
    root.ChemadvisorChemApi.RegulatoryList = factory(root.ChemadvisorChemApi.ApiClient, root.ChemadvisorChemApi.Entries, root.ChemadvisorChemApi.Languages, root.ChemadvisorChemApi.Links, root.ChemadvisorChemApi.Tags);
  }
}(this, function(ApiClient, Entries, Languages, Links, Tags) {
  'use strict';




  /**
   * The RegulatoryList model module.
   * @module chemadvisor.chemApi.model/RegulatoryList
   * @version 0.9.6 beta
   */

  /**
   * Constructs a new <code>RegulatoryList</code>.
   * Contains Substance Level Regulatory or Non-Regulatory Data
   * @alias module:chemadvisor.chemApi.model/RegulatoryList
   * @class
   * @param id {Integer} 
   * @param name {String} 
   * @param sourceLanguages {module:chemadvisor.chemApi.model/Languages} 
   */
  var exports = function(id, name, sourceLanguages) {
    var _this = this;

    _this['_id'] = id;
    _this['name'] = name;




    _this['source_languages'] = sourceLanguages;



  };

  /**
   * Constructs a <code>RegulatoryList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:chemadvisor.chemApi.model/RegulatoryList} obj Optional instance to populate.
   * @return {module:chemadvisor.chemApi.model/RegulatoryList} The populated <code>RegulatoryList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'Integer');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('navigator_link')) {
        obj['navigator_link'] = ApiClient.convertToType(data['navigator_link'], 'String');
      }
      if (data.hasOwnProperty('source_link')) {
        obj['source_link'] = ApiClient.convertToType(data['source_link'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('is_inventory')) {
        obj['is_inventory'] = ApiClient.convertToType(data['is_inventory'], 'Boolean');
      }
      if (data.hasOwnProperty('source_languages')) {
        obj['source_languages'] = Languages.constructFromObject(data['source_languages']);
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = Tags.constructFromObject(data['tags']);
      }
      if (data.hasOwnProperty('entries')) {
        obj['entries'] = Entries.constructFromObject(data['entries']);
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = Links.constructFromObject(data['links']);
      }
    }
    return obj;
  }

  /**
   * @member {Integer} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} navigator_link
   */
  exports.prototype['navigator_link'] = undefined;
  /**
   * @member {String} source_link
   */
  exports.prototype['source_link'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Boolean} is_inventory
   * @default false
   */
  exports.prototype['is_inventory'] = false;
  /**
   * @member {module:chemadvisor.chemApi.model/Languages} source_languages
   */
  exports.prototype['source_languages'] = undefined;
  /**
   * @member {module:chemadvisor.chemApi.model/Tags} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * @member {module:chemadvisor.chemApi.model/Entries} entries
   */
  exports.prototype['entries'] = undefined;
  /**
   * @member {module:chemadvisor.chemApi.model/Links} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


