/**
 * chemadvisor.io api
 * REST api to access ChemADVISOR maintained substance and regulatory data.
 *
 * OpenAPI spec version: 0.9.6 beta
 * Contact: support@chemadvisor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ChemadvisorChemApi);
  }
}(this, function(expect, ChemadvisorChemApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ChemadvisorChemApi.RegulatoryListChange();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RegulatoryListChange', function() {
    it('should create an instance of RegulatoryListChange', function() {
      // uncomment below and update the code to test RegulatoryListChange
      //var instane = new ChemadvisorChemApi.RegulatoryListChange();
      //expect(instance).to.be.a(ChemadvisorChemApi.RegulatoryListChange);
    });

    it('should have the property changeType (base name: "change_type")', function() {
      // uncomment below and update the code to test the property changeType
      //var instane = new ChemadvisorChemApi.RegulatoryListChange();
      //expect(instance).to.be();
    });

    it('should have the property regulatoryListId (base name: "regulatory_list_id")', function() {
      // uncomment below and update the code to test the property regulatoryListId
      //var instane = new ChemadvisorChemApi.RegulatoryListChange();
      //expect(instance).to.be();
    });

    it('should have the property releaseId (base name: "release_id")', function() {
      // uncomment below and update the code to test the property releaseId
      //var instane = new ChemadvisorChemApi.RegulatoryListChange();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instane = new ChemadvisorChemApi.RegulatoryListChange();
      //expect(instance).to.be();
    });

  });

}));
